ppw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

# views
from story_9.views import index, login_page, sign_up_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('login/', login_page, name='login-page'),
    path('sign-up/', sign_up_page, name='sign-up-page'),
    path('endpoint/', include(('story_9.urls', 'story_9'), namespace='endpoint'))
]

story_9/urls.py
from django.contrib import admin
from django.urls import path
# views
from story_9.views import login, sign_up, logout

urlpatterns = [
    path('login/', login, name='login'),
    path('sign-up/', sign_up, name='sign-up'),
    path('logout/', logout, name='logout')
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.http import HttpResponseBadRequest, HttpResponseNotAllowed, HttpResponseForbidden

# Models
from django.contrib.auth.models import User

# Pages
def index(request):
  if request.user.is_authenticated:
    return render(request, 'story_9/index.html')
  return redirect('login-page')

def login_page(request):
  return render(request, 'story_9/login-page.html')

def sign_up_page(request):
  return render(request, 'story_9/sign-up-page.html')

# Endpoints
def login(request):
  if request.method == 'POST':
    try:
      username = request.POST['username']
      password = request.POST['password']
    except KeyError:
      return HttpResponseBadRequest()

    user = auth.authenticate(request=request, username=username, password=password)
    if user is not None:
      auth.login(request, user)
      return redirect('home')
    else:
      messages.error(request, 'Invalid credentials')
      return redirect('login-page')
  return HttpResponseNotAllowed(permitted_methods=['POST'])

def sign_up(request):
  if request.method == 'POST':
    try:
      username = request.POST['username']
      password = request.POST['password']
      email = request.POST['email']
    except KeyError:
      return HttpResponseBadRequest()

    try:
      username_used = User.objects.get(username=username)
    except User.DoesNotExist:
      username_used = None

    try:
      email_used = User.objects.get(email=email)
    except User.DoesNotExist:
      email_used = None

    if username_used or email_used:
      if username_used:
        messages.error(request, 'Username already exists')
      if email_used:
        messages.error(request, 'Email already exists')
      return redirect('sign-up-page')

    User.objects.create_user(username, email=email, password=password)
    return redirect('login-page')

  return HttpResponseNotAllowed(permitted_methods=['POST'])

def logout(request):
  auth.logout(request)
  return redirect('login-page')

story_9/templates/story_9/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'story_9/main.css' %}">

  <!-- JS -->
  <script defer src="{% static 'story_9/main.js' %}"></script>

  <title>
    {% block title_block %}
    {% endblock %}
  </title>
</head>
<body>
  {% block content_block %}
  {% endblock %}
</body>
  {% block script_block %}
  {% endblock %}
</html>

story_9/templates/story_9/index.html
{% extends 'story_9/base.html' %}
{% block title_block %}
  story-9 | Home
{% endblock %}
{% block content_block %}
<div class="container d-flex justify-content-center align-items-center flex-column">
  <h1>Halo {{ user }}!</h1>
  <a href="{% url 'endpoint:logout' %}" class="btn btn-primary">Logout</a>
</div>
{% endblock %}

story_9/templates/story_9/login-page.html
{% extends 'story_9/base.html' %}
{% block title_block %}
  story-9 | Login
{% endblock %}
{% block content_block %}
<div class="container d-flex justify-content-center align-items-center flex-column">
  <h1>Login</h1>
  <small class='warning'>
    {% if messages %}
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    {% endif %}
  </small>
  <form method="POST" action="{% url 'endpoint:login' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" name='username' class="form-control" aria-describedby="emailHelp" placeholder="Enter username">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Enter password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
  <hr/>
  <small id="emailHelp" class="form-text text-muted">Don't have an account? <a href="{% url 'sign-up-page' %}">Sign up here</a></small>
</div>
{% endblock %}

story_9/templates/story_9/sign-up-page.html
{% extends 'story_9/base.html' %}
{% block title_block %}
  story-9 | Sign Up
{% endblock %}
{% block content_block %}
<div class="container d-flex justify-content-center align-items-center flex-column">
  <h1>Sign Up</h1>
  <div class='warning'>
    {% if messages %}
      {% for message in messages %}
        <small>{{ message }}</small>
      {% endfor %}
    {% endif %}
  </div>
  <form method="POST" action="{% url 'endpoint:sign-up' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" name='email' class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" name='username' class="form-control" aria-describedby="emailHelp" placeholder="Enter username">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Enter password">
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
  <hr/>
  <small id="emailHelp" class="form-text text-muted">Already have an account? <a href="{% url 'login-page' %}">Login here</a></small>
</div>
{% endblock %}